// Code generated by internal/capgen; DO NOT EDIT.

package shell

import (
	"image"
	"time"
)

// PostedAccessibility wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedAccessibility(inner Accessibility, post func(func())) Accessibility {
	if inner == nil || post == nil {
		return inner
	}
	return postedAccessibility{inner, post}
}

type postedAccessibility struct {
	inner Accessibility
	post  func(func())
}

func (p postedAccessibility) Announce(a0 string, a1 bool) {
	p.inner.Announce(a0, a1)
}

func (p postedAccessibility) SetTree(a0 []A11yNode, a1 func(id int)) {
	f1 := a1
	var w1 func(id int)
	if f1 != nil {
		w1 = func(c0 int) { p.post(func() { f1(c0) }) }
	}
	p.inner.SetTree(a0, w1)
}

// PostedAudio wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedAudio(inner Audio, post func(func())) Audio {
	if inner == nil || post == nil {
		return inner
	}
	return postedAudio{inner, post}
}

type postedAudio struct {
	inner Audio
	post  func(func())
}

func (p postedAudio) Authorize(a0 func(Permission)) {
	f0 := a0
	var w0 func(Permission)
	if f0 != nil {
		w0 = func(c0 Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedAudio) Record(a0 RecordOptions, a1 func(Recorder, error)) {
	f1 := a1
	var w1 func(Recorder, error)
	if f1 != nil {
		w1 = func(c0 Recorder, c1 error) { p.post(func() { f1(PostedRecorder(c0, p.post), c1) }) }
	}
	p.inner.Record(a0, w1)
}

func (p postedAudio) Play(a0 Clip, a1 func(Playback, error)) {
	f1 := a1
	var w1 func(Playback, error)
	if f1 != nil {
		w1 = func(c0 Playback, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Play(a0, w1)
}

// PostedBattery wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedBattery(inner Battery, post func(func())) Battery {
	if inner == nil || post == nil {
		return inner
	}
	return postedBattery{inner, post}
}

type postedBattery struct {
	inner Battery
	post  func(func())
}

func (p postedBattery) Level() float32 {
	return p.inner.Level()
}

func (p postedBattery) Charging() bool {
	return p.inner.Charging()
}

func (p postedBattery) OnChange(a0 func()) {
	f0 := a0
	var w0 func()
	if f0 != nil {
		w0 = func() { p.post(func() { f0() }) }
	}
	p.inner.OnChange(w0)
}

// PostedCamera wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedCamera(inner Camera, post func(func())) Camera {
	if inner == nil || post == nil {
		return inner
	}
	return postedCamera{inner, post}
}

type postedCamera struct {
	inner Camera
	post  func(func())
}

func (p postedCamera) Authorize(a0 func(Permission)) {
	f0 := a0
	var w0 func(Permission)
	if f0 != nil {
		w0 = func(c0 Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedCamera) Capture(a0 CaptureOptions, a1 func(img image.Image, err error)) {
	f1 := a1
	var w1 func(img image.Image, err error)
	if f1 != nil {
		w1 = func(c0 image.Image, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Capture(a0, w1)
}

// PostedConnectivity wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedConnectivity(inner Connectivity, post func(func())) Connectivity {
	if inner == nil || post == nil {
		return inner
	}
	return postedConnectivity{inner, post}
}

type postedConnectivity struct {
	inner Connectivity
	post  func(func())
}

func (p postedConnectivity) Online() bool {
	return p.inner.Online()
}

func (p postedConnectivity) OnChange(a0 func(online bool)) {
	f0 := a0
	var w0 func(online bool)
	if f0 != nil {
		w0 = func(c0 bool) { p.post(func() { f0(c0) }) }
	}
	p.inner.OnChange(w0)
}

// PostedFilePicker wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedFilePicker(inner FilePicker, post func(func())) FilePicker {
	if inner == nil || post == nil {
		return inner
	}
	return postedFilePicker{inner, post}
}

type postedFilePicker struct {
	inner FilePicker
	post  func(func())
}

func (p postedFilePicker) Open(a0 OpenOptions, a1 func(files []PickedFile, err error)) {
	f1 := a1
	var w1 func(files []PickedFile, err error)
	if f1 != nil {
		w1 = func(c0 []PickedFile, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Open(a0, w1)
}

func (p postedFilePicker) Save(a0 SaveOptions, a1 []byte, a2 func(err error)) {
	f2 := a2
	var w2 func(err error)
	if f2 != nil {
		w2 = func(c0 error) { p.post(func() { f2(c0) }) }
	}
	p.inner.Save(a0, a1, w2)
}

// PostedGeolocation wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedGeolocation(inner Geolocation, post func(func())) Geolocation {
	if inner == nil || post == nil {
		return inner
	}
	return postedGeolocation{inner, post}
}

type postedGeolocation struct {
	inner Geolocation
	post  func(func())
}

func (p postedGeolocation) Current(a0 func(lat, lon, accuracy float64, err error)) {
	f0 := a0
	var w0 func(lat, lon, accuracy float64, err error)
	if f0 != nil {
		w0 = func(c0 float64, c1 float64, c2 float64, c3 error) { p.post(func() { f0(c0, c1, c2, c3) }) }
	}
	p.inner.Current(w0)
}

func (p postedGeolocation) Watch(a0 func(lat, lon, accuracy float64)) func() {
	f0 := a0
	var w0 func(lat, lon, accuracy float64)
	if f0 != nil {
		w0 = func(c0 float64, c1 float64, c2 float64) { p.post(func() { f0(c0, c1, c2) }) }
	}
	return p.inner.Watch(w0)
}

// PostedLifecycle wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedLifecycle(inner Lifecycle, post func(func())) Lifecycle {
	if inner == nil || post == nil {
		return inner
	}
	return postedLifecycle{inner, post}
}

type postedLifecycle struct {
	inner Lifecycle
	post  func(func())
}

func (p postedLifecycle) State() AppState {
	return p.inner.State()
}

func (p postedLifecycle) OnChange(a0 func(AppState)) {
	f0 := a0
	var w0 func(AppState)
	if f0 != nil {
		w0 = func(c0 AppState) { p.post(func() { f0(c0) }) }
	}
	p.inner.OnChange(w0)
}

// PostedLinks wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedLinks(inner Links, post func(func())) Links {
	if inner == nil || post == nil {
		return inner
	}
	return postedLinks{inner, post}
}

type postedLinks struct {
	inner Links
	post  func(func())
}

func (p postedLinks) Initial() string {
	return p.inner.Initial()
}

func (p postedLinks) OnLink(a0 func(url string)) {
	f0 := a0
	var w0 func(url string)
	if f0 != nil {
		w0 = func(c0 string) { p.post(func() { f0(c0) }) }
	}
	p.inner.OnLink(w0)
}

// PostedMenus wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedMenus(inner Menus, post func(func())) Menus {
	if inner == nil || post == nil {
		return inner
	}
	return postedMenus{inner, post}
}

type postedMenus struct {
	inner Menus
	post  func(func())
}

func (p postedMenus) SetBar(a0 []Menu, a1 func(id int)) {
	f1 := a1
	var w1 func(id int)
	if f1 != nil {
		w1 = func(c0 int) { p.post(func() { f1(c0) }) }
	}
	p.inner.SetBar(a0, w1)
}

// PostedNotifier wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedNotifier(inner Notifier, post func(func())) Notifier {
	if inner == nil || post == nil {
		return inner
	}
	return postedNotifier{inner, post}
}

type postedNotifier struct {
	inner Notifier
	post  func(func())
}

func (p postedNotifier) Authorize(a0 func(Permission)) {
	f0 := a0
	var w0 func(Permission)
	if f0 != nil {
		w0 = func(c0 Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedNotifier) Notify(a0 Notification) {
	p.inner.Notify(a0)
}

// PostedPermissions wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedPermissions(inner Permissions, post func(func())) Permissions {
	if inner == nil || post == nil {
		return inner
	}
	return postedPermissions{inner, post}
}

type postedPermissions struct {
	inner Permissions
	post  func(func())
}

func (p postedPermissions) Status(a0 PermissionKind) Permission {
	return p.inner.Status(a0)
}

func (p postedPermissions) Request(a0 PermissionKind, a1 func(Permission)) {
	f1 := a1
	var w1 func(Permission)
	if f1 != nil {
		w1 = func(c0 Permission) { p.post(func() { f1(c0) }) }
	}
	p.inner.Request(a0, w1)
}

// PostedRecorder wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedRecorder(inner Recorder, post func(func())) Recorder {
	if inner == nil || post == nil {
		return inner
	}
	return postedRecorder{inner, post}
}

type postedRecorder struct {
	inner Recorder
	post  func(func())
}

func (p postedRecorder) Level() float32 {
	return p.inner.Level()
}

func (p postedRecorder) Elapsed() time.Duration {
	return p.inner.Elapsed()
}

func (p postedRecorder) Stop(a0 func(Clip, error)) {
	f0 := a0
	var w0 func(Clip, error)
	if f0 != nil {
		w0 = func(c0 Clip, c1 error) { p.post(func() { f0(c0, c1) }) }
	}
	p.inner.Stop(w0)
}

func (p postedRecorder) Cancel() {
	p.inner.Cancel()
}

// PostedShare wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedShare(inner Share, post func(func())) Share {
	if inner == nil || post == nil {
		return inner
	}
	return postedShare{inner, post}
}

type postedShare struct {
	inner Share
	post  func(func())
}

func (p postedShare) Share(a0 ShareItem, a1 func(err error)) {
	f1 := a1
	var w1 func(err error)
	if f1 != nil {
		w1 = func(c0 error) { p.post(func() { f1(c0) }) }
	}
	p.inner.Share(a0, w1)
}

// PostedSocket wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedSocket(inner Socket, post func(func())) Socket {
	if inner == nil || post == nil {
		return inner
	}
	return postedSocket{inner, post}
}

type postedSocket struct {
	inner Socket
	post  func(func())
}

func (p postedSocket) Dial(a0 string, a1 SocketHandlers) {
	s1 := a1
	w1 := s1
	if s1.OnOpen != nil {
		g := s1.OnOpen
		w1.OnOpen = func(c0 SocketConn) { p.post(func() { g(c0) }) }
	}
	if s1.OnMessage != nil {
		g := s1.OnMessage
		w1.OnMessage = func(c0 []byte) { p.post(func() { g(c0) }) }
	}
	if s1.OnText != nil {
		g := s1.OnText
		w1.OnText = func(c0 string) { p.post(func() { g(c0) }) }
	}
	if s1.OnClose != nil {
		g := s1.OnClose
		w1.OnClose = func(c0 error) { p.post(func() { g(c0) }) }
	}
	p.inner.Dial(a0, w1)
}

// PostedTextInput wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedTextInput(inner TextInput, post func(func())) TextInput {
	if inner == nil || post == nil {
		return inner
	}
	return postedTextInput{inner, post}
}

type postedTextInput struct {
	inner TextInput
	post  func(func())
}

func (p postedTextInput) Show(a0 TextInputOptions, a1 TextInputHandler) {
	s1 := a1
	w1 := s1
	if s1.OnText != nil {
		g := s1.OnText
		w1.OnText = func(c0 string) { p.post(func() { g(c0) }) }
	}
	if s1.OnComposing != nil {
		g := s1.OnComposing
		w1.OnComposing = func(c0 string) { p.post(func() { g(c0) }) }
	}
	if s1.OnEditKey != nil {
		g := s1.OnEditKey
		w1.OnEditKey = func(c0 EditKey) { p.post(func() { g(c0) }) }
	}
	p.inner.Show(a0, w1)
}

func (p postedTextInput) Hide() {
	p.inner.Hide()
}

func (p postedTextInput) SetText(a0 string, a1 int, a2 int) {
	p.inner.SetText(a0, a1, a2)
}

// PostedTray wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedTray(inner Tray, post func(func())) Tray {
	if inner == nil || post == nil {
		return inner
	}
	return postedTray{inner, post}
}

type postedTray struct {
	inner Tray
	post  func(func())
}

func (p postedTray) Show(a0 TrayItem, a1 func(id int)) {
	f1 := a1
	var w1 func(id int)
	if f1 != nil {
		w1 = func(c0 int) { p.post(func() { f1(c0) }) }
	}
	p.inner.Show(a0, w1)
}

func (p postedTray) Hide() {
	p.inner.Hide()
}
