// Code generated by internal/capgen; DO NOT EDIT.

package shell

import (
	"image"
	"time"
)

// PostedAudio wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedAudio(inner Audio, post func(func())) Audio {
	if inner == nil || post == nil {
		return inner
	}
	return postedAudio{inner, post}
}

type postedAudio struct {
	inner Audio
	post  func(func())
}

func (p postedAudio) Authorize(a0 func(Permission)) {
	f0 := a0
	var w0 func(Permission)
	if f0 != nil {
		w0 = func(c0 Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedAudio) Record(a0 RecordOptions, a1 func(Recorder, error)) {
	f1 := a1
	var w1 func(Recorder, error)
	if f1 != nil {
		w1 = func(c0 Recorder, c1 error) { p.post(func() { f1(PostedRecorder(c0, p.post), c1) }) }
	}
	p.inner.Record(a0, w1)
}

func (p postedAudio) Play(a0 Clip, a1 func(Playback, error)) {
	f1 := a1
	var w1 func(Playback, error)
	if f1 != nil {
		w1 = func(c0 Playback, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Play(a0, w1)
}

// PostedCamera wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedCamera(inner Camera, post func(func())) Camera {
	if inner == nil || post == nil {
		return inner
	}
	return postedCamera{inner, post}
}

type postedCamera struct {
	inner Camera
	post  func(func())
}

func (p postedCamera) Authorize(a0 func(Permission)) {
	f0 := a0
	var w0 func(Permission)
	if f0 != nil {
		w0 = func(c0 Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedCamera) Capture(a0 CaptureOptions, a1 func(img image.Image, err error)) {
	f1 := a1
	var w1 func(img image.Image, err error)
	if f1 != nil {
		w1 = func(c0 image.Image, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Capture(a0, w1)
}

// PostedFilePicker wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedFilePicker(inner FilePicker, post func(func())) FilePicker {
	if inner == nil || post == nil {
		return inner
	}
	return postedFilePicker{inner, post}
}

type postedFilePicker struct {
	inner FilePicker
	post  func(func())
}

func (p postedFilePicker) Open(a0 OpenOptions, a1 func(files []PickedFile, err error)) {
	f1 := a1
	var w1 func(files []PickedFile, err error)
	if f1 != nil {
		w1 = func(c0 []PickedFile, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Open(a0, w1)
}

func (p postedFilePicker) Save(a0 SaveOptions, a1 []byte, a2 func(err error)) {
	f2 := a2
	var w2 func(err error)
	if f2 != nil {
		w2 = func(c0 error) { p.post(func() { f2(c0) }) }
	}
	p.inner.Save(a0, a1, w2)
}

// PostedNotifier wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedNotifier(inner Notifier, post func(func())) Notifier {
	if inner == nil || post == nil {
		return inner
	}
	return postedNotifier{inner, post}
}

type postedNotifier struct {
	inner Notifier
	post  func(func())
}

func (p postedNotifier) Authorize(a0 func(Permission)) {
	f0 := a0
	var w0 func(Permission)
	if f0 != nil {
		w0 = func(c0 Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedNotifier) Notify(a0 Notification) {
	p.inner.Notify(a0)
}

// PostedPermissions wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedPermissions(inner Permissions, post func(func())) Permissions {
	if inner == nil || post == nil {
		return inner
	}
	return postedPermissions{inner, post}
}

type postedPermissions struct {
	inner Permissions
	post  func(func())
}

func (p postedPermissions) Status(a0 PermissionKind) Permission {
	return p.inner.Status(a0)
}

func (p postedPermissions) Request(a0 PermissionKind, a1 func(Permission)) {
	f1 := a1
	var w1 func(Permission)
	if f1 != nil {
		w1 = func(c0 Permission) { p.post(func() { f1(c0) }) }
	}
	p.inner.Request(a0, w1)
}

// PostedRecorder wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedRecorder(inner Recorder, post func(func())) Recorder {
	if inner == nil || post == nil {
		return inner
	}
	return postedRecorder{inner, post}
}

type postedRecorder struct {
	inner Recorder
	post  func(func())
}

func (p postedRecorder) Level() float32 {
	return p.inner.Level()
}

func (p postedRecorder) Elapsed() time.Duration {
	return p.inner.Elapsed()
}

func (p postedRecorder) Stop(a0 func(Clip, error)) {
	f0 := a0
	var w0 func(Clip, error)
	if f0 != nil {
		w0 = func(c0 Clip, c1 error) { p.post(func() { f0(c0, c1) }) }
	}
	p.inner.Stop(w0)
}

func (p postedRecorder) Cancel() {
	p.inner.Cancel()
}

// PostedShare wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func PostedShare(inner Share, post func(func())) Share {
	if inner == nil || post == nil {
		return inner
	}
	return postedShare{inner, post}
}

type postedShare struct {
	inner Share
	post  func(func())
}

func (p postedShare) Share(a0 ShareItem, a1 func(err error)) {
	f1 := a1
	var w1 func(err error)
	if f1 != nil {
		w1 = func(c0 error) { p.post(func() { f1(c0) }) }
	}
	p.inner.Share(a0, w1)
}
