name: GophicsHN
options:
  bundleIdPrefix: dev.gophics
  deploymentTarget:
    iOS: "15.0"
targets:
  GophicsHN:
    type: application
    platform: iOS
    sources:
      - GophicsHN
    dependencies:
      - framework: Hnmobile.xcframework
        embed: true
    info:
      path: GophicsHN/Info.plist
      properties:
        CFBundleDisplayName: gophics HN
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.gophics.hn
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
