package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

// The bind package is generated rather than written by hand.
//
// gomobile cannot bind `package main`, so something has to expose a bindable
// Start() for the native host to call. That constraint is real. Everything that
// grew on top of it was not: six examples each carried a mobile/ package, and
// four of them rebuilt app.Config by hand because the scaffold left Config() in
// package main where gomobile could not see it — so on a phone those apps
// quietly used a different font and background from the same app on the desktop.
//
// Nothing in that file is ever app-specific. It names the widget tree and the
// config, which the app already exports for its own main(), and hands them to
// app.NewHandler. So it is generated at build time from the convention below,
// and an app that needs something genuinely different keeps a mobile/ directory
// and is left alone.
//
// The frame loop, input, lifecycle, IME and accessibility are not passthroughs
// here: gomobileBind binds shell/mobile alongside this package, so the host
// calls Bridge methods directly. That was already true; the scaffold template
// had simply never been updated and still emitted forty hand-written wrappers.

// bindTmpl is the whole generated package.
var bindTmpl = template.Must(template.New("bind").Parse(
	`// Code generated by gophics; DO NOT EDIT.
//
// Package {{.Pkg}} is the gomobile-bind surface for {{.App}}. It exists because
// gomobile cannot bind package main; it holds nothing app-specific, and is
// regenerated on every mobile build.
//
// The host drives the app through the *mobile.Bridge this returns. The CLI
// binds shell/mobile alongside this package, so every Bridge method — frames,
// touch, keyboard, IME, accessibility, clipboard — is callable directly and
// needs no wrapper here.
package {{.Pkg}}

import (
	"github.com/doug/gophics/app"
	"github.com/doug/gophics/shell/mobile"

	ui "{{.UI}}"
)

// Start builds the app and returns the bridge the host drives it through.
//
// Call it once, before anything else. On failure it returns a nil bridge and
// the error to show — two results because the second is an error, which is the
// one shape gomobile allows.
func Start() (*mobile.Bridge, error) {
	h, err := app.NewHandler(ui.Root(), ui.Config())
	if err != nil {
		return nil, err
	}
	return mobile.NewBridge(h), nil
}
`))

type bindData struct {
	Pkg string // generated package name, e.g. hnmobile
	App string // app directory basename, e.g. hn
	UI  string // import path of the app's UI package
}

// resolveBindPkg returns the package path to hand gomobile.
//
// Three cases, in order:
//
//   - The package named on the command line is already a bind package (it is
//     not package main). Used as given — this is how `gophics run -p ios
//     ./examples/news/mobile` keeps working, and how an app with genuinely
//     app-specific host glue opts out.
//   - The app has a mobile/ directory next to it. Same thing, found by
//     convention rather than named.
//   - Otherwise the app is a plain main package, and the bind package is
//     generated under its build/ directory.
func resolveBindPkg(o buildOpts) (string, error) {
	name, err := packageName(o.pkg)
	if err != nil {
		return "", err
	}
	if name != "main" {
		return o.pkg, nil // already a bind package
	}

	dir, err := packageDir(o.pkg)
	if err != nil {
		return "", err
	}
	if isGoPkg(filepath.Join(dir, "mobile")) {
		return joinPkg(o.pkg, "mobile"), nil
	}
	return generateBindPkg(o, dir)
}

// generateBindPkg writes <app>/build/bind and returns its import path.
func generateBindPkg(o buildOpts, dir string) (string, error) {
	uiDir := filepath.Join(dir, "ui")
	if !isGoPkg(uiDir) {
		return "", fmt.Errorf(
			"%s has no ui/ package to bind.\n\n"+
				"A mobile build needs the widget tree in an importable package, because\n"+
				"gomobile cannot bind package main. Move Root() and Config() into %s/ui\n"+
				"and have main.go call them:\n\n"+
				"    func main() { app.Run(ui.Root(), ui.Config()) }\n\n"+
				"An app that needs its own bind surface can keep a mobile/ package\n"+
				"instead, and this step leaves it alone.",
			o.pkg, filepath.Base(dir))
	}
	uiPath, err := importPath(uiDir)
	if err != nil {
		return "", err
	}
	if err := checkUIExports(uiDir); err != nil {
		return "", err
	}

	app := filepath.Base(dir)
	data := bindData{Pkg: goIdent(app) + "mobile", App: app, UI: uiPath}

	out := filepath.Join(dir, "build", "bind")
	if err := os.MkdirAll(out, 0o755); err != nil {
		return "", err
	}
	f, err := os.Create(filepath.Join(out, "bind.go"))
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := bindTmpl.Execute(f, data); err != nil {
		return "", err
	}
	if err := f.Close(); err != nil {
		return "", err
	}

	appPath, err := importPath(dir)
	if err != nil {
		return "", err
	}
	return appPath + "/build/bind", nil
}

// checkUIExports fails early, with the fix, when the UI package does not follow
// the convention — rather than letting gomobile report an undefined symbol from
// inside generated code the user did not write.
func checkUIExports(uiDir string) error {
	var missing []string
	for _, want := range []string{"Root", "Config"} {
		out, err := exec.Command("go", "doc", uiDir, want).Output()
		if err != nil || len(strings.TrimSpace(string(out))) == 0 {
			missing = append(missing, want)
		}
	}
	if len(missing) == 0 {
		return nil
	}
	return fmt.Errorf(
		"%s does not export %s.\n\n"+
			"A mobile build reads the widget tree and the app config from the ui\n"+
			"package, so both the desktop entry point and the phone use the same\n"+
			"ones — four examples used to rebuild app.Config on the mobile side and\n"+
			"had drifted to a different font and background.\n\n"+
			"    func Root() widget.Widget { … }\n"+
			"    func Config() app.Config  { … }",
		uiDir, strings.Join(missing, " and "))
}

// isGoPkg reports whether dir exists and holds at least one .go file.
func isGoPkg(dir string) bool {
	ents, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range ents {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") {
			return true
		}
	}
	return false
}

// importPath resolves a directory to its Go import path.
func importPath(dir string) (string, error) {
	out, err := exec.Command("go", "list", "-f", "{{.ImportPath}}", dir).Output()
	if err != nil {
		return "", fmt.Errorf("resolve import path for %s: %w", dir, err)
	}
	return strings.TrimSpace(string(out)), nil
}

// joinPkg appends a subdirectory to a package path argument, keeping the
// leading ./ that distinguishes a path from an import path.
func joinPkg(pkg, sub string) string {
	return strings.TrimSuffix(pkg, "/") + "/" + sub
}

// goIdent makes a directory name usable as the start of a package identifier:
// lowercase, letters and digits only, never starting with a digit.
func goIdent(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= '0' && r <= '9' && b.Len() > 0:
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "app"
	}
	return b.String()
}

// ensureHost returns the native host project directory to build against,
// generating a throwaway one under build/ when the app does not carry its own.
//
// An app that keeps an ios/ or android/ directory owns it: hand-written hosts
// carry signing identities, entitlements, native sheets and permission strings,
// and regenerating over them would destroy work. Everything else gets the stock
// host, freshly rendered on every build — which is the point, because the five
// checked-in example hosts are byte-identical apart from their names and had
// already drifted from the templates they came from.
func ensureHost(o buildOpts) (string, error) {
	host, err := hostDirFor(o)
	if err != nil {
		return "", err
	}
	if dirExists(host) {
		return host, nil
	}
	if o.host != "" {
		return "", fmt.Errorf("-host %s does not exist", o.host)
	}

	dir, err := packageDir(o.pkg)
	if err != nil {
		return "", err
	}
	name := filepath.Base(dir)
	slug := goIdent(name)
	mobilePkg := slug + "mobile"
	bundleID := "com.example." + slug
	data := map[string]string{
		"Name":           name,
		"MobilePkg":      mobilePkg,
		"Framework":      titleFirst(mobilePkg),
		"BundleID":       bundleID,
		"BundleIDPrefix": "com.example",
		"AndroidPkg":     bundleID,
		"JNIPkg":         strings.ReplaceAll(bundleID, ".", "_"),
		"ProjectName":    titleFirst(slug),
	}

	root := filepath.Join(dir, "build", "host")
	ios := o.platform.name == "ios"
	if err := scaffoldMobile(root, bundleID, data, ios, !ios); err != nil {
		return "", fmt.Errorf("generate %s host: %w", o.platform.name, err)
	}
	out := filepath.Join(root, o.platform.name)
	fmt.Fprintf(os.Stderr,
		"gophics: no %s/ in %s — generated a stock host in %s\n"+
			"         (bundle id %s; keep your own %s/ directory to customise signing or native code)\n",
		o.platform.name, name, out, bundleID, o.platform.name)
	return out, nil
}

// bindPkgDir is the directory of the package gomobile will bind — the app's own
// mobile/ package, or the generated one. Capability scanning uses it rather
// than the command-line package because an app root is `package main`, which
// does not type-check for a mobile GOOS.
func bindPkgDir(o buildOpts) (string, error) {
	pkg, err := resolveBindPkg(o)
	if err != nil {
		return "", err
	}
	return packageDir(pkg)
}

// pruneStaleAARs removes every .aar in dir except keep, along with the
// -sources.jar gomobile writes beside each one.
//
// Silent about files it cannot remove: a stale artifact is a build-directory
// nuisance, and failing the build over one would be worse than the duplicate it
// prevents.
func pruneStaleAARs(dir, keep string) error {
	ents, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	keepBase := strings.TrimSuffix(keep, ".aar")
	for _, e := range ents {
		n := e.Name()
		if e.IsDir() || n == keep {
			continue
		}
		stale := strings.HasSuffix(n, ".aar") ||
			(strings.HasSuffix(n, "-sources.jar") && !strings.HasPrefix(n, keepBase+"-"))
		if !stale {
			continue
		}
		if err := os.Remove(filepath.Join(dir, n)); err == nil {
			fmt.Fprintf(os.Stderr, "gophics: removed stale app/libs/%s\n", n)
		}
	}
	return nil
}
