package cli

import (
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"runtime"
	"strconv"
	"syscall"
	"time"
)

// devHot runs the experimental state-aware hot-reload loop: it builds the app
// package as a Go plugin and runs a generated host that reloads the plugin's
// Root() through app.RunReloadable whenever sources change — no process
// restart, no window/GPU teardown.
//
// Go plugin constraints apply: linux/macOS only, and because a rebuilt plugin
// gets fresh type identities, app-defined widget State resets on reload
// (framework/host state persists). It's ideal for fast view iteration.
func devHot(o buildOpts) error {
	if runtime.GOOS != "linux" && runtime.GOOS != "darwin" {
		return fmt.Errorf("--hot needs Go plugins (linux/macOS only); use `gossamer dev -p web` or `gossamer dev` (hot-restart)")
	}
	hotDir := filepath.Join("build", "hot")
	hostDir := filepath.Join(hotDir, "host")
	if err := os.MkdirAll(hostDir, 0o755); err != nil {
		return err
	}
	current := filepath.Join(hotDir, "current")

	n := 0
	buildPlugin := func() (string, error) {
		so := filepath.Join(hotDir, fmt.Sprintf("app.%d.so", n))
		n++
		args := []string{"build", "-buildmode=plugin", "-o", so}
		if t := tagList(o.platform, o.gpu, o.tags); t != "" {
			args = append(args, "-tags", t)
		}
		args = append(args, o.pkg)
		if err := run("", nil, "go", args...); err != nil {
			return "", err
		}
		return so, nil
	}

	so, err := buildPlugin()
	if err != nil {
		return fmt.Errorf("plugin build (does %s export `func Root() widget.Widget`?): %w", o.pkg, err)
	}
	if err := os.WriteFile(current, []byte(so), 0o644); err != nil {
		return err
	}
	if err := writeTemplate(filepath.Join(hostDir, "main.go"), hostTmpl, map[string]string{
		"Current": filepath.ToSlash(current),
	}); err != nil {
		return err
	}

	host := exec.Command("go", "run", "./"+filepath.ToSlash(hostDir))
	host.Stdout, host.Stderr, host.Stdin = os.Stdout, os.Stderr, os.Stdin
	if err := host.Start(); err != nil {
		return fmt.Errorf("start hot host: %w", err)
	}
	defer func() {
		if host.Process != nil {
			_ = host.Process.Signal(syscall.SIGTERM)
			_ = host.Wait()
		}
	}()

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt, syscall.SIGTERM)
	changes, stop := watchSource(".", 250*time.Millisecond)
	defer stop()

	fmt.Fprintln(os.Stderr, "gossamer: --hot — edit & save to reload the view without restarting (Ctrl-C to stop)")
	fmt.Fprintln(os.Stderr, "gossamer: (note: app State resets per reload; see docs)")
	for {
		select {
		case <-sig:
			return nil
		case <-changes:
			fmt.Fprintln(os.Stderr, "gossamer: change — rebuilding plugin…")
			so, err := buildPlugin()
			if err != nil {
				fmt.Fprintf(os.Stderr, "gossamer: plugin build error (view unchanged):\n%v\n", err)
				continue
			}
			if err := os.WriteFile(current, []byte(so), 0o644); err != nil {
				fmt.Fprintf(os.Stderr, "gossamer: %v\n", err)
			}
		}
	}
}

var _ = strconv.Itoa // reserved for future host params

// hostTmpl is the generated hot-reload host. It runs in the app's module (so
// its framework version matches the plugin's), loads the plugin named in the
// `current` file, and reloads it through app.RunReloadable when that file
// changes.
const hostTmpl = `// Code generated by gossamer dev --hot. DO NOT EDIT.
package main

import (
	"log"
	"os"
	"plugin"
	"strings"
	"time"

	"golang.org/x/image/font/gofont/goregular"

	"github.com/doug/gossamer/app"
	"github.com/doug/gossamer/geom"
	"github.com/doug/gossamer/widget"
)

const currentFile = "{{.Current}}"

func load() (func() widget.Widget, app.Config, error) {
	path, err := os.ReadFile(currentFile)
	if err != nil {
		return nil, app.Config{}, err
	}
	p, err := plugin.Open(strings.TrimSpace(string(path)))
	if err != nil {
		return nil, app.Config{}, err
	}
	sym, err := p.Lookup("Root")
	if err != nil {
		return nil, app.Config{}, err
	}
	root, ok := sym.(func() widget.Widget)
	if !ok {
		return nil, app.Config{}, err
	}
	cfg := app.Config{Title: "gossamer dev", Size: geom.Size{W: 480, H: 720}, Font: goregular.TTF}
	if cs, err := p.Lookup("Config"); err == nil {
		if fn, ok := cs.(func() app.Config); ok {
			cfg = fn()
		}
	}
	return root, cfg, nil
}

func main() {
	root, cfg, err := load()
	if err != nil {
		log.Fatal("hot host: ", err)
	}
	reload := make(chan func() widget.Widget, 1)
	go func() {
		last, _ := os.ReadFile(currentFile)
		for range time.Tick(300 * time.Millisecond) {
			cur, _ := os.ReadFile(currentFile)
			if string(cur) == string(last) {
				continue
			}
			last = cur
			if r, _, err := load(); err == nil {
				reload <- r
			} else {
				log.Println("hot host reload:", err)
			}
		}
	}()
	if err := app.RunReloadable(root, cfg, reload); err != nil {
		log.Fatal(err)
	}
}
`
