package apisurface_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/doug/gophics/internal/apisurface"
)

// manifest is the committed public surface. It lives under design/ because it
// is a document as much as a fixture: the diff on a pull request is the review.
const manifest = "../../design/api-surface.txt"

// The public surface is a promise, so it is a committed artifact and a change
// to it is a change to the diff.
//
// PLAN.md §1.7 commits to "a small surface and the Go 1 compatibility ethos
// after 1.0". Before this test the number in that promise could only be
// asserted — every audit re-derived it by hand, and the last one shipped with a
// wrong conclusion in it. Now a refactor that claims to shrink the surface
// shows exactly what it removed, and one that grows it by accident cannot be
// merged quietly.
//
// GOPHICS_UPDATE_API=1 rewrites the file, the same convention apptest uses for
// golden images.
func TestPublicSurfaceMatchesManifest(t *testing.T) {
	got, err := apisurface.Collect("../..")
	if err != nil {
		t.Fatal(err)
	}
	if len(got) < 1000 {
		t.Fatalf("collected only %d exported identifiers; the scan is broken and "+
			"this test would pass while measuring nothing", len(got))
	}

	var b strings.Builder
	b.WriteString("# The public API surface of github.com/doug/gophics.\n")
	b.WriteString("# Generated by internal/apisurface; regenerate with GOPHICS_UPDATE_API=1 go test ./internal/apisurface\n")
	b.WriteString("#\n")
	b.WriteString("# Excludes internal/, examples/, cmd/, docs/, skills/ and shell/mobile\n")
	b.WriteString("# (a gomobile binding, versioned with the host app). See the package doc.\n")
	for _, e := range got {
		b.WriteString(string(e))
		b.WriteByte('\n')
	}
	want := b.String()

	if os.Getenv("GOPHICS_UPDATE_API") != "" {
		if err := os.MkdirAll(filepath.Dir(manifest), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(manifest, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d identifiers)", manifest, len(got))
		return
	}

	have, err := os.ReadFile(manifest)
	if err != nil {
		t.Fatalf("%v\n\nRun: GOPHICS_UPDATE_API=1 go test ./internal/apisurface", err)
	}
	if string(have) == want {
		t.Logf("public surface: %d identifiers", len(got))
		return
	}

	added, removed := diff(strings.Split(string(have), "\n"), strings.Split(want, "\n"))
	t.Errorf("the public API surface changed.\n\n"+
		"%d added, %d removed. If that is the intent, regenerate and let the diff\n"+
		"be reviewed:\n\n    GOPHICS_UPDATE_API=1 go test ./internal/apisurface\n\n%s",
		len(added), len(removed), sample(added, removed))
}

// The blind spot that produced a wrong conclusion, closed.
//
// The 2026-08-24 audit reported "nothing imports intl" and internalizing it was
// on the plan. examples/tally imports it and calls intl.Auto() — which reads
// LC_ALL and LANG, environment variables that do not exist on Android or iOS,
// where tally ships. The audit missed it because tally is a separate module and
// invisible to `go list ./...` from the root.
//
// Any future "no caller anywhere" claim has to survive this test.
func TestSeparateModulesAreVisibleToTheAudit(t *testing.T) {
	consumers, err := apisurface.Consumers("../..", "../../examples/tally")
	if err != nil {
		t.Fatal(err)
	}
	tallyUsers, ok := consumers["intl"]
	if !ok {
		t.Fatal("no consumer found for intl; the separate-module scan is not working, " +
			"which is exactly the hole that let 'nothing imports intl' be published")
	}
	var fromTally bool
	for _, c := range tallyUsers {
		if strings.Contains(c, "tally") {
			fromTally = true
		}
	}
	if !fromTally {
		t.Errorf("intl consumers = %v; expected one in the tally module", tallyUsers)
	}
}

func diff(have, want []string) (added, removed []string) {
	in := func(xs []string) map[string]bool {
		m := make(map[string]bool, len(xs))
		for _, x := range xs {
			if x != "" && !strings.HasPrefix(x, "#") {
				m[x] = true
			}
		}
		return m
	}
	h, w := in(have), in(want)
	for x := range w {
		if !h[x] {
			added = append(added, x)
		}
	}
	for x := range h {
		if !w[x] {
			removed = append(removed, x)
		}
	}
	return added, removed
}

func sample(added, removed []string) string {
	var b strings.Builder
	show := func(label string, xs []string) {
		if len(xs) == 0 {
			return
		}
		b.WriteString(label + "\n")
		for i, x := range xs {
			if i == 15 {
				b.WriteString("    … and " + itoa(len(xs)-15) + " more\n")
				break
			}
			b.WriteString("    " + x + "\n")
		}
	}
	show("added:", added)
	show("removed:", removed)
	return b.String()
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var d []byte
	for n > 0 {
		d = append([]byte{byte('0' + n%10)}, d...)
		n /= 10
	}
	return string(d)
}
