// Code generated by internal/capgen; DO NOT EDIT.

package widget

import "github.com/doug/gophics/shell"

// Capabilities holds the optional, platform-provided capabilities a Window may
// expose (see shell/*.go). It is embedded in Owner; its fields are promoted, so
// the Ctx accessors below read owner.<Cap> and apps read them via Ctx.<Cap>().
// Regenerate with: go generate ./...
type Capabilities struct {
	Audio         shell.Audio
	Camera        shell.Camera
	FilePicker    shell.FilePicker
	Haptic        shell.Haptic
	Notifier      shell.Notifier
	Permissions   shell.Permissions
	SecureStorage shell.SecureStorage
	Share         shell.Share
}

// Audio returns the platform Audio capability (shell.Audio), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Audio() shell.Audio { return c.el.owner.Audio }

// Camera returns the platform Camera capability (shell.Camera), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Camera() shell.Camera { return c.el.owner.Camera }

// FilePicker returns the platform FilePicker capability (shell.FilePicker), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) FilePicker() shell.FilePicker { return c.el.owner.FilePicker }

// Haptic returns the platform Haptic capability (shell.Haptic), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Haptic() shell.Haptic { return c.el.owner.Haptic }

// Notifier returns the platform Notifier capability (shell.Notifier), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Notifier() shell.Notifier { return c.el.owner.Notifier }

// Permissions returns the platform Permissions capability (shell.Permissions), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Permissions() shell.Permissions { return c.el.owner.Permissions }

// SecureStorage returns the platform SecureStorage capability (shell.SecureStorage), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) SecureStorage() shell.SecureStorage { return c.el.owner.SecureStorage }

// Share returns the platform Share capability (shell.Share), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Share() shell.Share { return c.el.owner.Share }
