// Code generated by internal/capgen; DO NOT EDIT.

package widget

import "github.com/doug/gophics/shell"

// Capabilities holds the optional, platform-provided capabilities a Window may
// expose (see shell/*.go). It is embedded in Owner; its fields are promoted, so
// the Ctx accessors below read owner.<Cap> and apps read them via Ctx.<Cap>().
// Regenerate with: go generate ./...
type Capabilities struct {
	Accessibility shell.Accessibility
	Battery       shell.Battery
	Biometric     shell.Biometric
	Camera        shell.Camera
	CameraPreview shell.CameraPreview
	Connectivity  shell.Connectivity
	FilePicker    shell.FilePicker
	Gamepads      shell.Gamepads
	Geolocation   shell.Geolocation
	Haptic        shell.Haptic
	Lifecycle     shell.Lifecycle
	Links         shell.Links
	Menus         shell.Menus
	Microphone    shell.Microphone
	Notifier      shell.Notifier
	Permissions   shell.Permissions
	Photos        shell.Photos
	Preferences   shell.Preferences
	SecureStorage shell.SecureStorage
	Share         shell.Share
	Socket        shell.Socket
	Speakers      shell.Speakers
	TextInput     shell.TextInput
	Tray          shell.Tray
	WakeLock      shell.WakeLock
	WebView       shell.WebView
	WindowControl shell.WindowControl
}

// Accessibility returns the platform Accessibility capability (shell.Accessibility), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Accessibility() shell.Accessibility { return c.el.owner.Accessibility }

// Battery returns the platform Battery capability (shell.Battery), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Battery() shell.Battery { return c.el.owner.Battery }

// Biometric returns the platform Biometric capability (shell.Biometric), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Biometric() shell.Biometric { return c.el.owner.Biometric }

// Camera returns the platform Camera capability (shell.Camera), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Camera() shell.Camera { return c.el.owner.Camera }

// CameraPreview returns the platform CameraPreview capability (shell.CameraPreview), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) CameraPreview() shell.CameraPreview { return c.el.owner.CameraPreview }

// Connectivity returns the platform Connectivity capability (shell.Connectivity), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Connectivity() shell.Connectivity { return c.el.owner.Connectivity }

// FilePicker returns the platform FilePicker capability (shell.FilePicker), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) FilePicker() shell.FilePicker { return c.el.owner.FilePicker }

// Gamepads returns the platform Gamepads capability (shell.Gamepads), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Gamepads() shell.Gamepads { return c.el.owner.Gamepads }

// Geolocation returns the platform Geolocation capability (shell.Geolocation), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Geolocation() shell.Geolocation { return c.el.owner.Geolocation }

// Haptic returns the platform Haptic capability (shell.Haptic), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Haptic() shell.Haptic { return c.el.owner.Haptic }

// Lifecycle returns the platform Lifecycle capability (shell.Lifecycle), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Lifecycle() shell.Lifecycle { return c.el.owner.Lifecycle }

// Links returns the platform Links capability (shell.Links), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Links() shell.Links { return c.el.owner.Links }

// Menus returns the platform Menus capability (shell.Menus), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Menus() shell.Menus { return c.el.owner.Menus }

// Microphone returns the platform Microphone capability (shell.Microphone), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Microphone() shell.Microphone { return c.el.owner.Microphone }

// Notifier returns the platform Notifier capability (shell.Notifier), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Notifier() shell.Notifier { return c.el.owner.Notifier }

// Permissions returns the platform Permissions capability (shell.Permissions), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Permissions() shell.Permissions { return c.el.owner.Permissions }

// Photos returns the platform Photos capability (shell.Photos), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Photos() shell.Photos { return c.el.owner.Photos }

// Preferences returns the platform Preferences capability (shell.Preferences), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Preferences() shell.Preferences { return c.el.owner.Preferences }

// SecureStorage returns the platform SecureStorage capability (shell.SecureStorage), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) SecureStorage() shell.SecureStorage { return c.el.owner.SecureStorage }

// Share returns the platform Share capability (shell.Share), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Share() shell.Share { return c.el.owner.Share }

// Socket returns the platform Socket capability (shell.Socket), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Socket() shell.Socket { return c.el.owner.Socket }

// Speakers returns the platform Speakers capability (shell.Speakers), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Speakers() shell.Speakers { return c.el.owner.Speakers }

// TextInput returns the platform TextInput capability (shell.TextInput), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) TextInput() shell.TextInput { return c.el.owner.TextInput }

// Tray returns the platform Tray capability (shell.Tray), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) Tray() shell.Tray { return c.el.owner.Tray }

// WakeLock returns the platform WakeLock capability (shell.WakeLock), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) WakeLock() shell.WakeLock { return c.el.owner.WakeLock }

// WebView returns the platform WebView capability (shell.WebView), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) WebView() shell.WebView { return c.el.owner.WebView }

// WindowControl returns the platform WindowControl capability (shell.WindowControl), or nil when the running
// platform can't provide it. See shell/*.go for its contract.
func (c Ctx) WindowControl() shell.WindowControl { return c.el.owner.WindowControl }
