// Code generated by internal/capgen; DO NOT EDIT.

package widget

import (
	"image"
	"time"

	"github.com/doug/gophics/shell"
)

// postedAccessibility wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedAccessibilityOf(inner shell.Accessibility, post func(func())) shell.Accessibility {
	if inner == nil || post == nil {
		return inner
	}
	return postedAccessibility{inner, post}
}

type postedAccessibility struct {
	inner shell.Accessibility
	post  func(func())
}

func (p postedAccessibility) Announce(a0 string, a1 bool) {
	p.inner.Announce(a0, a1)
}

func (p postedAccessibility) SetTree(a0 []shell.A11yNode, a1 func(id int)) {
	f1 := a1
	var w1 func(id int)
	if f1 != nil {
		w1 = func(c0 int) { p.post(func() { f1(c0) }) }
	}
	p.inner.SetTree(a0, w1)
}

// postedBattery wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedBatteryOf(inner shell.Battery, post func(func())) shell.Battery {
	if inner == nil || post == nil {
		return inner
	}
	return postedBattery{inner, post}
}

type postedBattery struct {
	inner shell.Battery
	post  func(func())
}

func (p postedBattery) Level() float32 {
	return p.inner.Level()
}

func (p postedBattery) Charging() bool {
	return p.inner.Charging()
}

func (p postedBattery) OnChange(a0 func()) {
	f0 := a0
	var w0 func()
	if f0 != nil {
		w0 = func() { p.post(func() { f0() }) }
	}
	p.inner.OnChange(w0)
}

// postedBiometric wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedBiometricOf(inner shell.Biometric, post func(func())) shell.Biometric {
	if inner == nil || post == nil {
		return inner
	}
	return postedBiometric{inner, post}
}

type postedBiometric struct {
	inner shell.Biometric
	post  func(func())
}

func (p postedBiometric) Available() shell.BiometricKind {
	return p.inner.Available()
}

func (p postedBiometric) Authenticate(a0 string, a1 bool, a2 func(ok bool, err error)) {
	f2 := a2
	var w2 func(ok bool, err error)
	if f2 != nil {
		w2 = func(c0 bool, c1 error) { p.post(func() { f2(c0, c1) }) }
	}
	p.inner.Authenticate(a0, a1, w2)
}

// postedCamera wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedCameraOf(inner shell.Camera, post func(func())) shell.Camera {
	if inner == nil || post == nil {
		return inner
	}
	return postedCamera{inner, post}
}

type postedCamera struct {
	inner shell.Camera
	post  func(func())
}

func (p postedCamera) Authorize(a0 func(shell.Permission)) {
	f0 := a0
	var w0 func(shell.Permission)
	if f0 != nil {
		w0 = func(c0 shell.Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedCamera) Capture(a0 shell.CaptureOptions, a1 func(img image.Image, err error)) {
	f1 := a1
	var w1 func(img image.Image, err error)
	if f1 != nil {
		w1 = func(c0 image.Image, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Capture(a0, w1)
}

// postedCameraPreview wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedCameraPreviewOf(inner shell.CameraPreview, post func(func())) shell.CameraPreview {
	if inner == nil || post == nil {
		return inner
	}
	return postedCameraPreview{inner, post}
}

type postedCameraPreview struct {
	inner shell.CameraPreview
	post  func(func())
}

func (p postedCameraPreview) Authorize(a0 func(shell.Permission)) {
	f0 := a0
	var w0 func(shell.Permission)
	if f0 != nil {
		w0 = func(c0 shell.Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedCameraPreview) Start(a0 shell.PreviewOptions, a1 func(shell.Frames, error)) {
	f1 := a1
	var w1 func(shell.Frames, error)
	if f1 != nil {
		w1 = func(c0 shell.Frames, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Start(a0, w1)
}

// postedConnectivity wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedConnectivityOf(inner shell.Connectivity, post func(func())) shell.Connectivity {
	if inner == nil || post == nil {
		return inner
	}
	return postedConnectivity{inner, post}
}

type postedConnectivity struct {
	inner shell.Connectivity
	post  func(func())
}

func (p postedConnectivity) Online() bool {
	return p.inner.Online()
}

func (p postedConnectivity) OnChange(a0 func(online bool)) {
	f0 := a0
	var w0 func(online bool)
	if f0 != nil {
		w0 = func(c0 bool) { p.post(func() { f0(c0) }) }
	}
	p.inner.OnChange(w0)
}

// postedFilePicker wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedFilePickerOf(inner shell.FilePicker, post func(func())) shell.FilePicker {
	if inner == nil || post == nil {
		return inner
	}
	return postedFilePicker{inner, post}
}

type postedFilePicker struct {
	inner shell.FilePicker
	post  func(func())
}

func (p postedFilePicker) Open(a0 shell.OpenOptions, a1 func(files []shell.PickedFile, err error)) {
	f1 := a1
	var w1 func(files []shell.PickedFile, err error)
	if f1 != nil {
		w1 = func(c0 []shell.PickedFile, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Open(a0, w1)
}

func (p postedFilePicker) Save(a0 shell.SaveOptions, a1 []byte, a2 func(err error)) {
	f2 := a2
	var w2 func(err error)
	if f2 != nil {
		w2 = func(c0 error) { p.post(func() { f2(c0) }) }
	}
	p.inner.Save(a0, a1, w2)
}

// postedGeolocation wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedGeolocationOf(inner shell.Geolocation, post func(func())) shell.Geolocation {
	if inner == nil || post == nil {
		return inner
	}
	return postedGeolocation{inner, post}
}

type postedGeolocation struct {
	inner shell.Geolocation
	post  func(func())
}

func (p postedGeolocation) Current(a0 func(lat, lon, accuracy float64, err error)) {
	f0 := a0
	var w0 func(lat, lon, accuracy float64, err error)
	if f0 != nil {
		w0 = func(c0 float64, c1 float64, c2 float64, c3 error) { p.post(func() { f0(c0, c1, c2, c3) }) }
	}
	p.inner.Current(w0)
}

func (p postedGeolocation) Watch(a0 func(lat, lon, accuracy float64)) func() {
	f0 := a0
	var w0 func(lat, lon, accuracy float64)
	if f0 != nil {
		w0 = func(c0 float64, c1 float64, c2 float64) { p.post(func() { f0(c0, c1, c2) }) }
	}
	return p.inner.Watch(w0)
}

// postedLifecycle wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedLifecycleOf(inner shell.Lifecycle, post func(func())) shell.Lifecycle {
	if inner == nil || post == nil {
		return inner
	}
	return postedLifecycle{inner, post}
}

type postedLifecycle struct {
	inner shell.Lifecycle
	post  func(func())
}

func (p postedLifecycle) State() shell.AppState {
	return p.inner.State()
}

func (p postedLifecycle) OnChange(a0 func(shell.AppState)) {
	f0 := a0
	var w0 func(shell.AppState)
	if f0 != nil {
		w0 = func(c0 shell.AppState) { p.post(func() { f0(c0) }) }
	}
	p.inner.OnChange(w0)
}

// postedLinks wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedLinksOf(inner shell.Links, post func(func())) shell.Links {
	if inner == nil || post == nil {
		return inner
	}
	return postedLinks{inner, post}
}

type postedLinks struct {
	inner shell.Links
	post  func(func())
}

func (p postedLinks) Initial() string {
	return p.inner.Initial()
}

func (p postedLinks) OnLink(a0 func(url string)) {
	f0 := a0
	var w0 func(url string)
	if f0 != nil {
		w0 = func(c0 string) { p.post(func() { f0(c0) }) }
	}
	p.inner.OnLink(w0)
}

// postedLocale wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedLocaleOf(inner shell.Locale, post func(func())) shell.Locale {
	if inner == nil || post == nil {
		return inner
	}
	return postedLocale{inner, post}
}

type postedLocale struct {
	inner shell.Locale
	post  func(func())
}

func (p postedLocale) Tag() string {
	return p.inner.Tag()
}

func (p postedLocale) OnChange(a0 func(tag string)) {
	f0 := a0
	var w0 func(tag string)
	if f0 != nil {
		w0 = func(c0 string) { p.post(func() { f0(c0) }) }
	}
	p.inner.OnChange(w0)
}

// postedMenus wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedMenusOf(inner shell.Menus, post func(func())) shell.Menus {
	if inner == nil || post == nil {
		return inner
	}
	return postedMenus{inner, post}
}

type postedMenus struct {
	inner shell.Menus
	post  func(func())
}

func (p postedMenus) SetBar(a0 []shell.Menu, a1 func(id int)) {
	f1 := a1
	var w1 func(id int)
	if f1 != nil {
		w1 = func(c0 int) { p.post(func() { f1(c0) }) }
	}
	p.inner.SetBar(a0, w1)
}

// postedMicrophone wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedMicrophoneOf(inner shell.Microphone, post func(func())) shell.Microphone {
	if inner == nil || post == nil {
		return inner
	}
	return postedMicrophone{inner, post}
}

type postedMicrophone struct {
	inner shell.Microphone
	post  func(func())
}

func (p postedMicrophone) Authorize(a0 func(shell.Permission)) {
	f0 := a0
	var w0 func(shell.Permission)
	if f0 != nil {
		w0 = func(c0 shell.Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedMicrophone) Listen(a0 func(shell.Monitor, error)) {
	f0 := a0
	var w0 func(shell.Monitor, error)
	if f0 != nil {
		w0 = func(c0 shell.Monitor, c1 error) { p.post(func() { f0(c0, c1) }) }
	}
	p.inner.Listen(w0)
}

func (p postedMicrophone) Record(a0 shell.RecordOptions, a1 func(shell.Recorder, error)) {
	f1 := a1
	var w1 func(shell.Recorder, error)
	if f1 != nil {
		w1 = func(c0 shell.Recorder, c1 error) { p.post(func() { f1(postedRecorderOf(c0, p.post), c1) }) }
	}
	p.inner.Record(a0, w1)
}

// postedNotifier wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedNotifierOf(inner shell.Notifier, post func(func())) shell.Notifier {
	if inner == nil || post == nil {
		return inner
	}
	return postedNotifier{inner, post}
}

type postedNotifier struct {
	inner shell.Notifier
	post  func(func())
}

func (p postedNotifier) Authorize(a0 func(shell.Permission)) {
	f0 := a0
	var w0 func(shell.Permission)
	if f0 != nil {
		w0 = func(c0 shell.Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedNotifier) Notify(a0 shell.Notification) {
	p.inner.Notify(a0)
}

// postedPermissions wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedPermissionsOf(inner shell.Permissions, post func(func())) shell.Permissions {
	if inner == nil || post == nil {
		return inner
	}
	return postedPermissions{inner, post}
}

type postedPermissions struct {
	inner shell.Permissions
	post  func(func())
}

func (p postedPermissions) Status(a0 shell.PermissionKind) shell.Permission {
	return p.inner.Status(a0)
}

func (p postedPermissions) Request(a0 shell.PermissionKind, a1 func(shell.Permission)) {
	f1 := a1
	var w1 func(shell.Permission)
	if f1 != nil {
		w1 = func(c0 shell.Permission) { p.post(func() { f1(c0) }) }
	}
	p.inner.Request(a0, w1)
}

// postedPhotos wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedPhotosOf(inner shell.Photos, post func(func())) shell.Photos {
	if inner == nil || post == nil {
		return inner
	}
	return postedPhotos{inner, post}
}

type postedPhotos struct {
	inner shell.Photos
	post  func(func())
}

func (p postedPhotos) Authorize(a0 func(shell.Permission)) {
	f0 := a0
	var w0 func(shell.Permission)
	if f0 != nil {
		w0 = func(c0 shell.Permission) { p.post(func() { f0(c0) }) }
	}
	p.inner.Authorize(w0)
}

func (p postedPhotos) Save(a0 []byte, a1 string, a2 func(err error)) {
	f2 := a2
	var w2 func(err error)
	if f2 != nil {
		w2 = func(c0 error) { p.post(func() { f2(c0) }) }
	}
	p.inner.Save(a0, a1, w2)
}

// postedRecorder wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedRecorderOf(inner shell.Recorder, post func(func())) shell.Recorder {
	if inner == nil || post == nil {
		return inner
	}
	return postedRecorder{inner, post}
}

type postedRecorder struct {
	inner shell.Recorder
	post  func(func())
}

func (p postedRecorder) Level() float32 {
	return p.inner.Level()
}

func (p postedRecorder) Elapsed() time.Duration {
	return p.inner.Elapsed()
}

func (p postedRecorder) Stop(a0 func(shell.Clip, error)) {
	f0 := a0
	var w0 func(shell.Clip, error)
	if f0 != nil {
		w0 = func(c0 shell.Clip, c1 error) { p.post(func() { f0(c0, c1) }) }
	}
	p.inner.Stop(w0)
}

func (p postedRecorder) Cancel() {
	p.inner.Cancel()
}

// postedShare wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedShareOf(inner shell.Share, post func(func())) shell.Share {
	if inner == nil || post == nil {
		return inner
	}
	return postedShare{inner, post}
}

type postedShare struct {
	inner shell.Share
	post  func(func())
}

func (p postedShare) Share(a0 shell.ShareItem, a1 func(err error)) {
	f1 := a1
	var w1 func(err error)
	if f1 != nil {
		w1 = func(c0 error) { p.post(func() { f1(c0) }) }
	}
	p.inner.Share(a0, w1)
}

// postedSocket wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedSocketOf(inner shell.Socket, post func(func())) shell.Socket {
	if inner == nil || post == nil {
		return inner
	}
	return postedSocket{inner, post}
}

type postedSocket struct {
	inner shell.Socket
	post  func(func())
}

func (p postedSocket) Dial(a0 string, a1 shell.SocketHandlers) {
	s1 := a1
	w1 := s1
	if s1.OnOpen != nil {
		g := s1.OnOpen
		w1.OnOpen = func(c0 shell.SocketConn) { p.post(func() { g(c0) }) }
	}
	if s1.OnMessage != nil {
		g := s1.OnMessage
		w1.OnMessage = func(c0 []byte) { p.post(func() { g(c0) }) }
	}
	if s1.OnText != nil {
		g := s1.OnText
		w1.OnText = func(c0 string) { p.post(func() { g(c0) }) }
	}
	if s1.OnClose != nil {
		g := s1.OnClose
		w1.OnClose = func(c0 error) { p.post(func() { g(c0) }) }
	}
	p.inner.Dial(a0, w1)
}

// postedSpeakers wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedSpeakersOf(inner shell.Speakers, post func(func())) shell.Speakers {
	if inner == nil || post == nil {
		return inner
	}
	return postedSpeakers{inner, post}
}

type postedSpeakers struct {
	inner shell.Speakers
	post  func(func())
}

func (p postedSpeakers) Play(a0 shell.Clip, a1 func(shell.Playback, error)) {
	f1 := a1
	var w1 func(shell.Playback, error)
	if f1 != nil {
		w1 = func(c0 shell.Playback, c1 error) { p.post(func() { f1(c0, c1) }) }
	}
	p.inner.Play(a0, w1)
}

// postedTextInput wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedTextInputOf(inner shell.TextInput, post func(func())) shell.TextInput {
	if inner == nil || post == nil {
		return inner
	}
	return postedTextInput{inner, post}
}

type postedTextInput struct {
	inner shell.TextInput
	post  func(func())
}

func (p postedTextInput) Show(a0 shell.TextInputOptions, a1 shell.TextInputHandler) {
	s1 := a1
	w1 := s1
	if s1.OnText != nil {
		g := s1.OnText
		w1.OnText = func(c0 string) { p.post(func() { g(c0) }) }
	}
	if s1.OnComposing != nil {
		g := s1.OnComposing
		w1.OnComposing = func(c0 string) { p.post(func() { g(c0) }) }
	}
	if s1.OnEditKey != nil {
		g := s1.OnEditKey
		w1.OnEditKey = func(c0 shell.EditKey) { p.post(func() { g(c0) }) }
	}
	if s1.OnReplace != nil {
		g := s1.OnReplace
		w1.OnReplace = func(c0 int, c1 int, c2 string) { p.post(func() { g(c0, c1, c2) }) }
	}
	p.inner.Show(a0, w1)
}

func (p postedTextInput) Hide() {
	p.inner.Hide()
}

func (p postedTextInput) SetText(a0 string, a1 int, a2 int) {
	p.inner.SetText(a0, a1, a2)
}

// postedTray wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedTrayOf(inner shell.Tray, post func(func())) shell.Tray {
	if inner == nil || post == nil {
		return inner
	}
	return postedTray{inner, post}
}

type postedTray struct {
	inner shell.Tray
	post  func(func())
}

func (p postedTray) Show(a0 shell.TrayItem, a1 func(id int)) {
	f1 := a1
	var w1 func(id int)
	if f1 != nil {
		w1 = func(c0 int) { p.post(func() { f1(c0) }) }
	}
	p.inner.Show(a0, w1)
}

func (p postedTray) Hide() {
	p.inner.Hide()
}

// postedWakeLock wraps inner so every callback it (or anything it hands out)
// invokes is delivered through post — the app runner passes Owner.Post, making
// the "callbacks fire on the UI goroutine" contract hold no matter which
// goroutine the platform implementation completes on. Nil-safe: a nil inner
// returns nil, and a nil post returns inner unwrapped (callbacks fire inline).
func postedWakeLockOf(inner shell.WakeLock, post func(func())) shell.WakeLock {
	if inner == nil || post == nil {
		return inner
	}
	return postedWakeLock{inner, post}
}

type postedWakeLock struct {
	inner shell.WakeLock
	post  func(func())
}

func (p postedWakeLock) Acquire(a0 string) func() {
	return p.inner.Acquire(a0)
}

func (p postedWakeLock) Held() bool {
	return p.inner.Held()
}
