// Code generated by internal/capgen; DO NOT EDIT.

package widget

import "github.com/doug/gophics/shell"

// WireCapabilities publishes each capability the Window opts into (by
// implementing the matching shell.<X>Window) to the widget Owner. A window that
// doesn't implement a given interface leaves that capability nil. Callback-
// carrying capabilities are wrapped in a posted adapter so every
// callback is delivered on the UI goroutine via Owner.Post, regardless of which
// goroutine the platform implementation completes on.
// It is a method on Owner rather than a function in app because it uses
// nothing from app: only shell, the Owner it writes to, and Owner.Post. Living
// here is what lets the Capabilities fields and the posted wrappers stay
// unexported — an app names ctx.<Cap>(), never the plumbing.
func (o *Owner) WireCapabilities(w shell.Window) {
	if x, ok := w.(shell.AccessibilityWindow); ok {
		o.accessibility = postedAccessibilityOf(x.Accessibility(), o.Post)
	}
	if x, ok := w.(shell.BatteryWindow); ok {
		o.battery = postedBatteryOf(x.Battery(), o.Post)
	}
	if x, ok := w.(shell.BiometricWindow); ok {
		o.biometric = postedBiometricOf(x.Biometric(), o.Post)
	}
	if x, ok := w.(shell.CameraPreviewWindow); ok {
		o.cameraPreview = postedCameraPreviewOf(x.CameraPreview(), o.Post)
	}
	if x, ok := w.(shell.CameraWindow); ok {
		o.camera = postedCameraOf(x.Camera(), o.Post)
	}
	if x, ok := w.(shell.ConnectivityWindow); ok {
		o.connectivity = postedConnectivityOf(x.Connectivity(), o.Post)
	}
	if x, ok := w.(shell.FilePickerWindow); ok {
		o.filePicker = postedFilePickerOf(x.FilePicker(), o.Post)
	}
	if x, ok := w.(shell.GamepadWindow); ok {
		o.gamepads = x.Gamepads()
	}
	if x, ok := w.(shell.GeolocationWindow); ok {
		o.geolocation = postedGeolocationOf(x.Geolocation(), o.Post)
	}
	if x, ok := w.(shell.HapticWindow); ok {
		o.haptic = x.Haptic()
	}
	if x, ok := w.(shell.LifecycleWindow); ok {
		o.lifecycle = postedLifecycleOf(x.Lifecycle(), o.Post)
	}
	if x, ok := w.(shell.LinksWindow); ok {
		o.links = postedLinksOf(x.Links(), o.Post)
	}
	if x, ok := w.(shell.LocaleWindow); ok {
		o.locale = postedLocaleOf(x.Locale(), o.Post)
	}
	if x, ok := w.(shell.MenuWindow); ok {
		o.menus = postedMenusOf(x.Menus(), o.Post)
	}
	if x, ok := w.(shell.MicrophoneWindow); ok {
		o.microphone = postedMicrophoneOf(x.Microphone(), o.Post)
	}
	if x, ok := w.(shell.NotifyWindow); ok {
		o.notifier = postedNotifierOf(x.Notifier(), o.Post)
	}
	if x, ok := w.(shell.PermissionWindow); ok {
		o.permissions = postedPermissionsOf(x.Permissions(), o.Post)
	}
	if x, ok := w.(shell.PhotosWindow); ok {
		o.photos = postedPhotosOf(x.Photos(), o.Post)
	}
	if x, ok := w.(shell.PreferencesWindow); ok {
		o.preferences = x.Preferences()
	}
	if x, ok := w.(shell.ShareWindow); ok {
		o.share = postedShareOf(x.Share(), o.Post)
	}
	if x, ok := w.(shell.SocketWindow); ok {
		o.socket = postedSocketOf(x.Socket(), o.Post)
	}
	if x, ok := w.(shell.SpeakersWindow); ok {
		o.speakers = postedSpeakersOf(x.Speakers(), o.Post)
	}
	if x, ok := w.(shell.StorageWindow); ok {
		o.secureStorage = x.SecureStorage()
	}
	if x, ok := w.(shell.TextInputWindow); ok {
		o.textInput = postedTextInputOf(x.TextInput(), o.Post)
	}
	if x, ok := w.(shell.TrayWindow); ok {
		o.tray = postedTrayOf(x.Tray(), o.Post)
	}
	if x, ok := w.(shell.WakeLockWindow); ok {
		o.wakeLock = postedWakeLockOf(x.WakeLock(), o.Post)
	}
	if x, ok := w.(shell.WebViewWindow); ok {
		o.webView = x.WebView()
	}
	if x, ok := w.(shell.WindowControlWindow); ok {
		o.windowControl = x.WindowControl()
	}
}

// Accessibility returns the platform Accessibility capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Accessibility().
func (o *Owner) Accessibility() shell.Accessibility { return o.accessibility }

// Battery returns the platform Battery capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Battery().
func (o *Owner) Battery() shell.Battery { return o.battery }

// Biometric returns the platform Biometric capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Biometric().
func (o *Owner) Biometric() shell.Biometric { return o.biometric }

// Camera returns the platform Camera capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Camera().
func (o *Owner) Camera() shell.Camera { return o.camera }

// CameraPreview returns the platform CameraPreview capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.CameraPreview().
func (o *Owner) CameraPreview() shell.CameraPreview { return o.cameraPreview }

// Connectivity returns the platform Connectivity capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Connectivity().
func (o *Owner) Connectivity() shell.Connectivity { return o.connectivity }

// FilePicker returns the platform FilePicker capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.FilePicker().
func (o *Owner) FilePicker() shell.FilePicker { return o.filePicker }

// Gamepads returns the platform Gamepads capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Gamepads().
func (o *Owner) Gamepads() shell.Gamepads { return o.gamepads }

// Geolocation returns the platform Geolocation capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Geolocation().
func (o *Owner) Geolocation() shell.Geolocation { return o.geolocation }

// Haptic returns the platform Haptic capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Haptic().
func (o *Owner) Haptic() shell.Haptic { return o.haptic }

// Lifecycle returns the platform Lifecycle capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Lifecycle().
func (o *Owner) Lifecycle() shell.Lifecycle { return o.lifecycle }

// Links returns the platform Links capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Links().
func (o *Owner) Links() shell.Links { return o.links }

// Locale returns the platform Locale capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Locale().
func (o *Owner) Locale() shell.Locale { return o.locale }

// Menus returns the platform Menus capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Menus().
func (o *Owner) Menus() shell.Menus { return o.menus }

// Microphone returns the platform Microphone capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Microphone().
func (o *Owner) Microphone() shell.Microphone { return o.microphone }

// Notifier returns the platform Notifier capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Notifier().
func (o *Owner) Notifier() shell.Notifier { return o.notifier }

// Permissions returns the platform Permissions capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Permissions().
func (o *Owner) Permissions() shell.Permissions { return o.permissions }

// Photos returns the platform Photos capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Photos().
func (o *Owner) Photos() shell.Photos { return o.photos }

// Preferences returns the platform Preferences capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Preferences().
func (o *Owner) Preferences() shell.Preferences { return o.preferences }

// SecureStorage returns the platform SecureStorage capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.SecureStorage().
func (o *Owner) SecureStorage() shell.SecureStorage { return o.secureStorage }

// Share returns the platform Share capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Share().
func (o *Owner) Share() shell.Share { return o.share }

// Socket returns the platform Socket capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Socket().
func (o *Owner) Socket() shell.Socket { return o.socket }

// Speakers returns the platform Speakers capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Speakers().
func (o *Owner) Speakers() shell.Speakers { return o.speakers }

// TextInput returns the platform TextInput capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.TextInput().
func (o *Owner) TextInput() shell.TextInput { return o.textInput }

// Tray returns the platform Tray capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.Tray().
func (o *Owner) Tray() shell.Tray { return o.tray }

// WakeLock returns the platform WakeLock capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.WakeLock().
func (o *Owner) WakeLock() shell.WakeLock { return o.wakeLock }

// WebView returns the platform WebView capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.WebView().
func (o *Owner) WebView() shell.WebView { return o.webView }

// WindowControl returns the platform WindowControl capability, or nil when the running
// platform cannot provide it. Widgets read it through Ctx.WindowControl().
func (o *Owner) WindowControl() shell.WindowControl { return o.windowControl }
