// Code generated by internal/capgen; DO NOT EDIT.

package app

import (
	"github.com/doug/gophics/shell"
	"github.com/doug/gophics/widget"
)

// wireCapabilities publishes each capability the Window opts into (by
// implementing the matching shell.<X>Window) to the widget Owner. A window that
// doesn't implement a given interface leaves that capability nil.
func wireCapabilities(o *widget.Owner, w shell.Window) {
	if x, ok := w.(shell.FilePickerWindow); ok {
		o.FilePicker = x.FilePicker()
	}
	if x, ok := w.(shell.HapticWindow); ok {
		o.Haptic = x.Haptic()
	}
	if x, ok := w.(shell.MediaWindow); ok {
		o.Audio = x.Audio()
		o.Camera = x.Camera()
	}
	if x, ok := w.(shell.NotifyWindow); ok {
		o.Notifier = x.Notifier()
	}
	if x, ok := w.(shell.PermissionWindow); ok {
		o.Permissions = x.Permissions()
	}
	if x, ok := w.(shell.ShareWindow); ok {
		o.Share = x.Share()
	}
	if x, ok := w.(shell.StorageWindow); ok {
		o.SecureStorage = x.SecureStorage()
	}
}
