// Code generated by internal/capgen; DO NOT EDIT.

package app

import (
	"github.com/doug/gophics/shell"
	"github.com/doug/gophics/widget"
)

// wireCapabilities publishes each capability the Window opts into (by
// implementing the matching shell.<X>Window) to the widget Owner. A window that
// doesn't implement a given interface leaves that capability nil. Callback-
// carrying capabilities are wrapped in their shell.Posted<Cap> adapter so every
// callback is delivered on the UI goroutine via Owner.Post, regardless of which
// goroutine the platform implementation completes on.
func wireCapabilities(o *widget.Owner, w shell.Window) {
	if x, ok := w.(shell.AccessibilityWindow); ok {
		o.Accessibility = shell.PostedAccessibility(x.Accessibility(), o.Post)
	}
	if x, ok := w.(shell.BatteryWindow); ok {
		o.Battery = shell.PostedBattery(x.Battery(), o.Post)
	}
	if x, ok := w.(shell.ConnectivityWindow); ok {
		o.Connectivity = shell.PostedConnectivity(x.Connectivity(), o.Post)
	}
	if x, ok := w.(shell.FilePickerWindow); ok {
		o.FilePicker = shell.PostedFilePicker(x.FilePicker(), o.Post)
	}
	if x, ok := w.(shell.GamepadWindow); ok {
		o.Gamepads = x.Gamepads()
	}
	if x, ok := w.(shell.GeolocationWindow); ok {
		o.Geolocation = shell.PostedGeolocation(x.Geolocation(), o.Post)
	}
	if x, ok := w.(shell.HapticWindow); ok {
		o.Haptic = x.Haptic()
	}
	if x, ok := w.(shell.LifecycleWindow); ok {
		o.Lifecycle = shell.PostedLifecycle(x.Lifecycle(), o.Post)
	}
	if x, ok := w.(shell.LinksWindow); ok {
		o.Links = shell.PostedLinks(x.Links(), o.Post)
	}
	if x, ok := w.(shell.MediaWindow); ok {
		o.Audio = shell.PostedAudio(x.Audio(), o.Post)
		o.Camera = shell.PostedCamera(x.Camera(), o.Post)
	}
	if x, ok := w.(shell.MenuWindow); ok {
		o.Menus = shell.PostedMenus(x.Menus(), o.Post)
	}
	if x, ok := w.(shell.NotifyWindow); ok {
		o.Notifier = shell.PostedNotifier(x.Notifier(), o.Post)
	}
	if x, ok := w.(shell.PermissionWindow); ok {
		o.Permissions = shell.PostedPermissions(x.Permissions(), o.Post)
	}
	if x, ok := w.(shell.PreferencesWindow); ok {
		o.Preferences = x.Preferences()
	}
	if x, ok := w.(shell.ShareWindow); ok {
		o.Share = shell.PostedShare(x.Share(), o.Post)
	}
	if x, ok := w.(shell.SocketWindow); ok {
		o.Socket = shell.PostedSocket(x.Socket(), o.Post)
	}
	if x, ok := w.(shell.StorageWindow); ok {
		o.SecureStorage = x.SecureStorage()
	}
	if x, ok := w.(shell.TextInputWindow); ok {
		o.TextInput = shell.PostedTextInput(x.TextInput(), o.Post)
	}
	if x, ok := w.(shell.WebViewWindow); ok {
		o.WebView = x.WebView()
	}
	if x, ok := w.(shell.WindowControlWindow); ok {
		o.WindowControl = x.WindowControl()
	}
}
