package app

import (
	"log"

	"github.com/doug/gophics/internal/gfx/gg"

	"github.com/doug/gophics/geom"
	"github.com/doug/gophics/paint"
	"github.com/doug/gophics/shell"
)

// wireMedia publishes the window's optional platform capabilities (camera,
// audio, haptics, file picker, …) to the widget tree, leaving each nil when the
// window doesn't implement its shell.<X>Window. The per-capability wiring is
// generated by wireCapabilities (app/capabilities_gen.go) from the shell
// interfaces — see internal/capgen/README.md.
func (h *shellHandler) wireMedia(w shell.Window) {
	h.core.Owner.WireCapabilities(w)
}

// wireWindow wires the window-backed Owner hooks (clipboard, OpenURL,
// capabilities) once per window. The wiring is identity-stable — rebuilding the
// Posted<Cap> adapters and closures every frame was pure per-frame garbage — so
// it re-runs only when the shell hands us a different Window.
//
// The tree mounts (Init + first Build) inside newCore, before any shell exists,
// so capabilities are nil then; they only become available here, on the first
// frame. Marking the tree dirty when they first arrive lets Build re-read them —
// otherwise an app that reads ctx.<Cap>() would see it nil until an unrelated
// state change.
//
// Build, and only Build. Init does not run again: a State's Init fires once,
// when the State is created (see updateChild), and RebuildAll only marks the
// tree dirty. So a widget must not decide anything permanent about a capability
// in Init — a check there runs while every capability is still nil and is never
// revisited. Read them in Build, or re-check in a Ticker.
//
// This is easy to get wrong and silent when you do: the capability is simply
// absent forever, with no error and nothing in the logs.
func (h *shellHandler) wireWindow(w shell.Window) {
	// The platform's fling curve, unless the app pinned one in Config.
	if h.core.Owner.ScrollPhysics.Model == shell.FlingPlatform {
		if p, ok := w.(shell.ScrollPhysicsProvider); ok {
			h.core.Owner.ScrollPhysics = p.ScrollPhysics()
		}
	}
	if h.wired == w {
		return
	}
	h.wired = w
	h.core.Owner.Clipboard = w
	h.core.Owner.OpenURL = w.OpenURL
	h.wireMedia(w)
	h.core.Owner.RebuildAll()
}

// gpuCanvasTarget is a frame Target that rasterizes on the GPU: RenderGPU runs
// the scene replay against a GPU-backed gg.Context, then composites the result
// to the surface. A shell whose resolved renderer is GPU returns one once its
// GPU canvas is ready; otherwise it returns a CPU PixelTarget and present()
// takes the CPU path below. Selection is per-frame, so a shell can serve CPU
// frames while its GPU device is still initializing, then switch over.
type gpuCanvasTarget interface {
	RenderGPU(replay func(*gg.Context))
}

// gpuSkipTarget is optionally implemented by GPU targets that must be told when
// a frame deliberately renders nothing. The desktop shell needs it: gogpu
// treats an OnDraw that produced no GPU work as a failed frame-begin and
// schedules a recovery redraw, which would turn every skipped frame into a
// busy loop. Web and mobile acquire their swapchain texture inside RenderGPU
// itself, so simply not calling it presents nothing and needs no signal.
type gpuSkipTarget interface {
	SkipRenderGPU()
}

// present rasterizes the recorded scene for one frame. When the frame offers a
// GPU target the whole scene is replayed on the GPU — but only when it changed:
// an unchanged scene skips the replay entirely and the last presented frame
// stays on screen. Otherwise the CPU rasterizer paints the damaged region and
// hands finished pixels to the shell.
//
// The GPU skip is safe against the swapchain because every GPU shell (web,
// desktop, mobile) acquires its swapchain frame lazily — web and mobile call
// GetCurrentTexture inside RenderGPU, and gogpu on desktop defers the acquire
// to the first draw call — so skipping the replay acquires nothing and leaves
// no frame dangling. The one shell-side wrinkle is desktop's recovery redraw,
// handled via gpuSkipTarget above.
//
// A target the handler has not presented to yet (the first GPU frame, the
// web/mobile switchover from the pending/CPU path, a recreated device surface
// after backgrounding) must render even when the scene is unchanged: its
// swapchain has never shown this scene. Target identity tracks that — each
// shell's GPU target value is stable per surface generation.
func (h *shellHandler) present(f shell.Frame, tgt shell.Target, changed bool, damage geom.Rect) {
	if gt, ok := tgt.(gpuCanvasTarget); ok {
		if !changed && gt == h.lastGPU {
			if st, ok := tgt.(gpuSkipTarget); ok {
				st.SkipRenderGPU()
			}
			return
		}
		gt.RenderGPU(func(cc *gg.Context) {
			// The GPU rasterizes the whole frame each time; replay in full.
			h.core.ReplayScene(h.core.Painter.GPUCanvas(cc))
		})
		h.lastGPU = gt
		return
	}
	h.lastGPU = nil
	if changed {
		canvas := h.core.Painter.BeginOffscreen(f.Size(), f.Scale())
		h.core.ReplayDamaged(canvas, damage)
	}
	// Present even when skipped: the painter's surface is retained, and the
	// swapchain still needs this frame's image.
	//
	// Damage is scaled to physical pixels here because that is where the
	// coordinate space changes: everything above works in logical units — Diff
	// produces a logical rect, and ReplayDamaged clips a canvas that carries
	// the device-scale transform — while the surface handed over below is the
	// physical pixmap. Passing the logical rect against a physical image is a
	// silent HiDPI bug: at 2x it names the top-left quadrant's rows, so a
	// presenter that honours it uploads half the height and leaves the rest
	// holding the previous frame.
	if err := presentSurface(h.core.Painter, tgt, scaleRect(damage, f.Scale())); err != nil {
		log.Printf("gophics: present: %v", err)
	}
}

// scaleRect converts a logical rect to physical pixels. An empty rect stays
// empty: it means "nothing changed", and scaling that would invent a region.
func scaleRect(r geom.Rect, scale float32) geom.Rect {
	if r.IsEmpty() || scale == 1 {
		return r
	}
	return geom.Rect{
		Min: geom.Pt{X: r.Min.X * scale, Y: r.Min.Y * scale},
		Max: geom.Pt{X: r.Max.X * scale, Y: r.Max.Y * scale},
	}
}

// presentSurface hands the painter's finished CPU surface to the shell's
// target, with damage already in the surface's physical pixels.
func presentSurface(p *paint.Painter, tgt shell.Target, damage geom.Rect) error {
	switch t := tgt.(type) {
	case shell.PixelTarget:
		if s := p.SurfaceRGBA(); s != nil {
			t.Put(s, damage)
		}
	}
	return nil
}

// presentDropped keeps the previous frame on screen after a layout/paint panic
// dropped this one: a GPU target is deliberately skipped (nothing acquired,
// desktop told not to re-request), a CPU target re-presents the painter's
// retained surface (a no-op before the first frame has rasterized).
func (h *shellHandler) presentDropped(f shell.Frame, tgt shell.Target) {
	if _, ok := tgt.(gpuCanvasTarget); ok {
		if st, ok := tgt.(gpuSkipTarget); ok {
			st.SkipRenderGPU()
		}
		return
	}
	// Nothing was drawn, so nothing is damaged: the host re-presents whatever
	// it already had.
	_ = presentSurface(h.core.Painter, tgt, geom.Rect{})
}
