// Command capgen generates the platform-capability plumbing from the
// shell.<X>Window interfaces, so adding a capability never means hand-editing
// widget.Owner, the Ctx accessors, and the app-runner wiring in lockstep.
//
// It scans shell/*.go for every interface named "<X>Window" (other than the base
// Window) whose methods are all zero-argument, single-interface-result getters —
// the capability-provider convention (MediaWindow.Camera() Camera, etc.) — and
// emits:
//
//	widget/capabilities_gen.go  — the Capabilities struct (embedded in Owner) plus
//	                              a Ctx.<Cap>() accessor for each capability
//	app/capabilities_gen.go     — wireCapabilities(owner, window): one type-assert
//	                              per <X>Window, publishing what the window exposes
//
// Run via `go generate ./...` (see widget/gen.go). The generator locates the
// module root itself, so the working directory doesn't matter.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type capability struct{ Field, Type string } // e.g. {"Camera", "Camera"} → owner.Camera shell.Camera

type capWindow struct {
	Name string // e.g. "MediaWindow"
	Caps []capability
}

func main() {
	root, err := moduleRoot()
	if err != nil {
		fail(err)
	}
	windows, caps := parseShell(filepath.Join(root, "shell"))
	if len(caps) == 0 {
		fail(fmt.Errorf("no capability windows found under shell/"))
	}
	writeWidget(root, caps)
	writeApp(root, windows)
}

// moduleRoot walks up from the working directory to the dir holding go.mod.
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("capgen: go.mod not found above %s", dir)
		}
		dir = parent
	}
}

// parseShell finds the capability-provider interfaces and their capabilities.
func parseShell(dir string) (windows []capWindow, caps []capability) {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		fail(err)
	}
	seen := map[string]capability{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, 0)
		if err != nil {
			fail(err)
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				name := ts.Name.Name
				if name == "Window" || !strings.HasSuffix(name, "Window") {
					continue
				}
				it, ok := ts.Type.(*ast.InterfaceType)
				if !ok {
					continue
				}
				w, ok := capsOf(name, it)
				if !ok {
					continue
				}
				windows = append(windows, w)
				for _, c := range w.Caps {
					seen[c.Field] = c
				}
			}
		}
	}
	sort.Slice(windows, func(i, j int) bool { return windows[i].Name < windows[j].Name })
	for _, c := range seen {
		caps = append(caps, c)
	}
	sort.Slice(caps, func(i, j int) bool { return caps[i].Field < caps[j].Field })
	return windows, caps
}

// capsOf returns the capabilities of a candidate <X>Window interface, and false
// if any method isn't a zero-arg, single-interface-result getter (so it's not a
// capability provider).
func capsOf(name string, it *ast.InterfaceType) (capWindow, bool) {
	w := capWindow{Name: name}
	for _, m := range it.Methods.List {
		if len(m.Names) != 1 {
			return w, false // embedded interface, not a getter
		}
		ft, ok := m.Type.(*ast.FuncType)
		if !ok {
			return w, false
		}
		if ft.Params != nil && len(ft.Params.List) != 0 {
			return w, false
		}
		if ft.Results == nil || len(ft.Results.List) != 1 {
			return w, false
		}
		id, ok := ft.Results.List[0].Type.(*ast.Ident)
		if !ok {
			return w, false // qualified/pointer result — not a same-package capability
		}
		w.Caps = append(w.Caps, capability{Field: m.Names[0].Name, Type: id.Name})
	}
	if len(w.Caps) == 0 {
		return w, false
	}
	sort.Slice(w.Caps, func(i, j int) bool { return w.Caps[i].Field < w.Caps[j].Field })
	return w, true
}

func writeWidget(root string, caps []capability) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/capgen; DO NOT EDIT.\n\n")
	b.WriteString("package widget\n\n")
	b.WriteString("import \"github.com/doug/gophics/shell\"\n\n")
	b.WriteString("// Capabilities holds the optional, platform-provided capabilities a Window may\n")
	b.WriteString("// expose (see shell/*.go). It is embedded in Owner; its fields are promoted, so\n")
	b.WriteString("// the Ctx accessors below read owner.<Cap> and apps read them via Ctx.<Cap>().\n")
	b.WriteString("// Regenerate with: go generate ./...\n")
	b.WriteString("type Capabilities struct {\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "\t%s shell.%s\n", c.Field, c.Type)
	}
	b.WriteString("}\n\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "// %s returns the platform %s capability (shell.%s), or nil when the running\n", c.Field, c.Field, c.Type)
		fmt.Fprintf(&b, "// platform can't provide it. See shell/*.go for its contract.\n")
		fmt.Fprintf(&b, "func (c Ctx) %s() shell.%s { return c.el.owner.%s }\n\n", c.Field, c.Type, c.Field)
	}
	writeFormatted(filepath.Join(root, "widget", "capabilities_gen.go"), b.Bytes())
}

func writeApp(root string, windows []capWindow) {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/capgen; DO NOT EDIT.\n\n")
	b.WriteString("package app\n\n")
	b.WriteString("import (\n\t\"github.com/doug/gophics/shell\"\n\t\"github.com/doug/gophics/widget\"\n)\n\n")
	b.WriteString("// wireCapabilities publishes each capability the Window opts into (by\n")
	b.WriteString("// implementing the matching shell.<X>Window) to the widget Owner. A window that\n")
	b.WriteString("// doesn't implement a given interface leaves that capability nil.\n")
	b.WriteString("func wireCapabilities(o *widget.Owner, w shell.Window) {\n")
	for _, win := range windows {
		fmt.Fprintf(&b, "\tif x, ok := w.(shell.%s); ok {\n", win.Name)
		for _, c := range win.Caps {
			fmt.Fprintf(&b, "\t\to.%s = x.%s()\n", c.Field, c.Field)
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n")
	writeFormatted(filepath.Join(root, "app", "capabilities_gen.go"), b.Bytes())
}

func writeFormatted(path string, src []byte) {
	out, err := format.Source(src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "capgen: format %s: %v\n----\n%s\n----\n", path, err, src)
		os.Exit(1)
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		fail(err)
	}
	fmt.Println("capgen: wrote", path)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "capgen:", err)
	os.Exit(1)
}
