#!/usr/bin/env bash
# android.sh — bind the Go side and assemble the APK.
#
#   ./package/android.sh            # debug APK, installed and launched if a
#                                   # device or emulator is attached
#   ./package/android.sh --release  # release APK (needs a keystore; see README)
#
# The bind surface is generated by the CLI (gomobile cannot bind package main,
# and this app keeps no mobile/ package of its own), so the whole loop goes
# through `gophics`: it writes build/bind, binds it with the shell bridge into
# android/app/libs, and drives the gradle wrapper under a JDK it has checked.
# Binding by hand here was how this script pointed at a ./mobile directory
# that does not exist.
set -euo pipefail
cd "$(dirname "$0")/.."

GOPHICS="${GOPHICS:-go run github.com/doug/gophics/cmd/gophics}"

# The SDK location: gradle reads local.properties, which is machine-specific and
# not committed.
if [ ! -f android/local.properties ] && [ -d "$HOME/Library/Android/sdk" ]; then
  echo "sdk.dir=$HOME/Library/Android/sdk" > android/local.properties
fi

if [ "${1:-}" = "--release" ]; then
  # A release build is assembled by gradle directly, after the CLI has bound
  # the Go side (gophics build leaves the .aar under build/android; the host
  # links whatever is in app/libs, so it is copied there).
  $GOPHICS build -p android .
  mkdir -p android/app/libs
  rm -f android/app/libs/*.aar
  cp build/android/app.aar android/app/libs/tallymobile.aar
  (cd android && ./gradlew --no-daemon assembleRelease)
  find android/app/build/outputs/apk -name '*.apk' -print
  exit 0
fi

exec $GOPHICS run -p android .
