#!/usr/bin/env bash
# ios.sh — bind the Go side, generate the Xcode project, build for the simulator.
#
#   ./package/ios.sh          # build, install and launch on a booted simulator
#   ./package/ios.sh --device # the same on a connected device (needs a team)
#
# The bind surface is generated by the CLI (gomobile cannot bind package main,
# and this app keeps no mobile/ package of its own), so the whole loop goes
# through `gophics`: it writes build/bind, binds it with the shell bridge into
# ios/Tallymobile.xcframework, runs xcodegen over ios/project.yml, and builds
# and installs with xcodebuild. Binding by hand here was how this script
# pointed at a ./mobile directory that does not exist.
set -euo pipefail
cd "$(dirname "$0")/.."

GOPHICS="${GOPHICS:-go run github.com/doug/gophics/cmd/gophics}"

if [ "${1:-}" = "--device" ]; then
  exec $GOPHICS run -p ios -device .
fi
exec $GOPHICS run -p ios .
